<?php

/**
 * Example of config/channel.generated.php — the real file is what
 * `bin/console theme:sync` writes from your live EMR channel, and it is
 * gitignored (`payment_processor.config` carries live provider credentials,
 * e.g. API keys). This example is committed so the shape is documented
 * without ever putting real secrets in version control; every value below is
 * a placeholder.
 *
 * GENERATED by bin/console theme:sync — do not hand-edit structural keys.
 * Hand-added operational keys survive re-sync (merge semantics): add your own
 * key anywhere in this tree (e.g. a 'debug_log' flag inside
 * payment_processor.config) and it will still be there after the next sync,
 * as long as theme:sync's own payload doesn't also set that same key.
 */
return [
    'channel' => [
        'id' => 'REPLACE_ME_CHANNEL_ID',
        'name' => 'Example Channel',
    ],
    'payment_processor' => [
        'provider_category' => 'vrio',
        'name' => 'Example Payment Processor',
        'config' => [
            'integration_name' => 'Example',
            'api_endpoint' => 'https://api.example.test',
            'app_base_url' => 'https://storefront.example.test',
            'api_key' => 'REPLACE_ME',
            'connection_id' => 'REPLACE_ME',
            'campaign_id' => 'REPLACE_ME',
            // Hand-added: the EMR channel payload has no shipping profile, so
            // theme:sync never writes this and never overwrites it (merge
            // semantics, above). The provider refuses any order carrying a
            // payment action without one, and refuses a profile that does not
            // belong to the campaign — so a wrong value fails every checkout
            // rather than degrading. `config/payment.php` holds the value the
            // application actually reads; this entry is here so an operator
            // reading the processor block knows the provider wants one.
            'shipping_profile_id' => 'REPLACE_ME',
        ],
    ],
];
