<?php

/**
 * Example of config/channel.generated.php — the real file is what
 * `bin/console theme:sync` writes from your live EMR channel, and it is
 * gitignored (`payment_processor.config` carries live provider credentials,
 * e.g. API keys). This example is committed so the shape is documented
 * without ever putting real secrets in version control; every value below is
 * a placeholder.
 *
 * GENERATED by bin/console theme:sync — do not hand-edit.
 *
 * Hand-added keys survive a re-sync of the same channel, with two exceptions
 * that matter:
 *
 *  - The whole `payment_processor` block is REPLACED on every sync. Every key
 *    in it is the configured provider's own vocabulary, written by the EMR, and
 *    nothing in this codebase reads a hand-added key from it — the shipping
 *    profile is read from config/payment.php, the wire-log switch from
 *    app.debug.wire_log. Merging it would only ever keep a key the configured
 *    provider has no use for, or a credential belonging to a provider this
 *    deployment no longer talks to.
 *  - Pointing the deployment at a DIFFERENT channel replaces this file
 *    wholesale. Nothing written for the old channel describes the new one.
 *
 * So put your own operational keys outside `payment_processor`, and treat
 * everything inside it as read-only output.
 */
return [
    'channel' => [
        'id' => 'REPLACE_ME_CHANNEL_ID',
        'name' => 'Example Channel',
    ],
    'payment_processor' => [
        'provider_category' => 'vrio',
        'name' => 'Example Payment Processor',
        'config' => [
            'integration_name' => 'Example',
            'api_endpoint' => 'https://api.example.test',
            'app_base_url' => 'https://storefront.example.test',
            'api_key' => 'REPLACE_ME',
            'connection_id' => 'REPLACE_ME',
            'campaign_id' => 'REPLACE_ME',
            // NOT hand-addable here any more: this block is replaced on every
            // sync (see above), so a value written here is gone after the next
            // one. It is shown because the provider does want a shipping
            // profile — it refuses any order carrying a payment action without
            // one, and refuses a profile that does not belong to the campaign,
            // so a wrong value fails every checkout rather than degrading.
            // `config/payment.php` is where the application reads it from, and
            // that is where a deployment sets it.
            'shipping_profile_id' => 'REPLACE_ME',
        ],
    ],
];
